Update __main__ to work again
* Fix `yaml TypeError: load() missing 1 required positional argument: 'Loader'` https://github.com/yaml/pyyaml/pull/561
* wait for bot.run(), this broke when moving to asyncio
  `RuntimeWarning: coroutine 'Bot.run' was never awaited`