Don't throw an exception when a message has no text
By switching from `split(' ')` to `split()` the following behavior changed

  >>> ''.split()
  []
  >>> ''.split(' ')
  ['']

So now args could be an empty list. The impact of this issue is just a noisy
exception and nothing else, as if the text is empty it won't have a '!' in it
and cannot be a command

  Traceback (most recent call last):
    File "slackminion-2.0.0-py3-none-any.whl/slackminion/bot.py", line 319, in _event_message
      cmd, output, cmd_options = await self.dispatcher.push(msg, self.dev_mode)
    File "slackminion-2.0.0-py3-none-any.whl/slackminion/dispatcher.py", line 79, in push
      if not args[0].startswith('!'):
  IndexError: list index out of range

Bump version to 2.0.1 to fix this minor bug

Introduced in 09bc4a43b48549e2202a78bcd735e7d05e8d84db